apiRules:
- exclude:
    uidRegex: ^Microsoft\.AspNetCore\.Mvc\.Controller(Base)?
    type: Type
- exclude:
    uidRegex: Microsoft.AspNetCore.Mvc.Filters
    type: Type
- exclude:
    uidRegex: Microsoft.AspNetCore.Identity
    type: Type
- exclude:
    uidRegex: Microsoft.EntityFrameworkCore.DbContext
    type: Type
- exclude:
    uidRegex: ^System\.Object
    type: Type
- exclude:
    uidRegex: ^System\.Collections
    type: Type